### ISSUE TITLE
Coursedrawer Wishlist

### ISSUE THREAD

**Issue by TinyCrocodile** [TinyCrocodile/Coursedrawer#11]
I know there is a lot to do but still i would like to know what improvements of the Coursegenerator are most wanted.

If somebody finds this just let me know what you wold like to have i see what i can do. 
Note: I am not a professional programmer, i can't promise i can fix it.

**Comment by LazyChilla** [comment]
Hello. I'd wish that coursedrawer could handle bigger maps (eg 4 fach nf marsch or even 16x cornbelt). It is a pitty you cannot see courses completely in the present version.
Thx for fixing it.

**Comment by TinyCrocodile** [comment]
@pAnFarmer  witch version of Couresdrawer did you use? Can you pleas create a separate issue and add a coursfile with a cours that didnt work. So i can test it. I have no 4x or 16x maps and have not time to start with this.

**Comment by LazyChilla** [comment]
@TinyCrocodile Hello and thx for the answer. I try my best. Now I've got the time to reply. Since I am not sure, if I can handle the opening of an new issue at the right place, I put it here. Version: 5.1.0.21418

To give you an ortientation I add some screenshots of the course called "GeSi-Pferdehof" and the view of the map. "Pferdehof" is to be found at the top-right corner. This is only one course-example that is "too big".
This course is already not displayed completely without zooming. With zooming it gets even worse. The "workarea" of coursedrawer is/gets to small.
![nordfriesische-marsch-4fach-map](https://user-images.githubusercontent.com/35901206/36528754-7768884e-17b6-11e8-825c-ca61926bdbf3.jpg)
The normal sized map would be a bit more than the Zuckerfabrik-Obstfarm-Kartoffelfabrik-Weberei-square.
![2018-02-22 1](https://user-images.githubusercontent.com/35901206/36528782-8ea52012-17b6-11e8-8fbb-071efa1714c2.png)
![2018-02-22 2](https://user-images.githubusercontent.com/35901206/36528783-8ebe1450-17b6-11e8-9433-a4f4813eeae2.png)
![2018-02-22](https://user-images.githubusercontent.com/35901206/36528784-8ed688be-17b6-11e8-8c86-1651a4614397.png)
I hope you can see what the issue is and fix it.
I will send you the coursemanager.xml by email. I cannot find out how to put it here. Sorry.

Another question: How can I reduce the zoomfactor?

Thx for your work and help.

**Comment by LazyChilla** [comment]
@TinyCrocodile Hello and thx for the answer. I try my best. Now I've got the time to reply. Since I am not sure, if I can handle the opening of an new issue at the right place, I put it here. Version: 5.1.0.21418

To give you an ortientation I add some screenshots of the course called "GeSi-Pferdehof" and the view of the map. "Pferdehof" is to be found at the top-right corner. This is only one course-example that is "too big".
This course is already not displayed completely without zooming. With zooming it gets even worse. The "workarea" of coursedrawer is/gets to small.
![nordfriesische-marsch-4fach-map](https://user-images.githubusercontent.com/35901206/36528754-7768884e-17b6-11e8-825c-ca61926bdbf3.jpg)
The normal sized map would be a bit more than the Zuckerfabrik-Obstfarm-Kartoffelfabrik-Weberei-square.
![2018-02-22 1](https://user-images.githubusercontent.com/35901206/36528782-8ea52012-17b6-11e8-8fbb-071efa1714c2.png)
![2018-02-22 2](https://user-images.githubusercontent.com/35901206/36528783-8ebe1450-17b6-11e8-9433-a4f4813eeae2.png)
![2018-02-22](https://user-images.githubusercontent.com/35901206/36528784-8ed688be-17b6-11e8-8c86-1651a4614397.png)
I hope you can see what the issue is and fix it.
I will send you the coursemanager.xml by email. I cannot find out how to put it here. Sorry.

Another question: How can I reduce the zoomfactor?

Thx for your work and help.

Gesendet von Mail für Windows 10

Von: TinyCrocodile
Gesendet: Sonntag, 18. Februar 2018 19:07
An: TinyCrocodile/Coursedrawer
Cc: pAnFarmer; Mention
Betreff: Re: [TinyCrocodile/Coursedrawer] Coursedrawer Wishlist (#11)

@pAnFarmer witch version of Couresdrawer did you use? Can you pleas create a separate issue and add a coursfile with a cours that didnt work. So i can test it. I have no 4x or 16x maps and have not time to start with this.

**Comment by TinyCrocodile** [comment]
@pAnFarmer  thank you for this information
You can Put the courses xml in a Zip file and drag and drop it into the answer. 
In the Beta-Release 5.2 i already tryed to fix this problem by making a Combobox to select the used Map Size.
You can get this Version here: [https://github.com/TinyCrocodile/Coursedrawer/releases](url). 
You can try this version or load a bitmap with the size of 4096x4096 (even if it is empty) this should solve the problem at the moment.
I hope to publish beta 5.3 soon. If posible i decrease the minimal zoomfactor in version 5.3 this may be helpful for big map overview.

**Comment by LazyChilla** [comment]
@TinyCrocodile Thx a lot. The suggested version works fine. Meanwhile I solve the zooming back problem by just restarting coursedrawer. Is ok for me.
Have fun!!!

**Comment by TinyCrocodile** [comment]
@pAnFarmer when in zooming mode you can zoom back by clicking the right Mousebutton and zoom in by clicking the left mousebutton. The minimal zoomfactor is 50% at the moment.

**Comment by LazyChilla** [comment]
@TinyCrocodile Oh, cool. Didn't know that. So no more need to exit program. Another great feature.
Have fun!!! Thx.
